import yfinance as yf
import pandas as pd
import finnhub
import os
import datetime
from dotenv import load_dotenv

load_dotenv()

class DataCollector:
    def __init__(self, ticker, start_date=None, end_date=None):
        self.ticker = ticker
        # Default to 1 year of data if not specified
        self.start_date = start_date if start_date else (datetime.date.today() - datetime.timedelta(days=365)).strftime("%Y-%m-%d")
        self.end_date = end_date if end_date else datetime.date.today().strftime("%Y-%m-%d")
        
        api_key = os.getenv('FINNHUB_API_KEY')
        self.finnhub_client = finnhub.Client(api_key=api_key) if api_key else None

    def fetch_stock_data(self):
        """
        Fetches historical stock prices using yfinance.
        Calculates basic technical indicators and target labels.
        """
        print(f"Fetching stock data for {self.ticker} from {self.start_date} to {self.end_date}...")
        stock = yf.Ticker(self.ticker)
        df = stock.history(start=self.start_date, end=self.end_date)
        
        if df.empty:
            print("Warning: No stock data found!")
            return pd.DataFrame()
            
        # Ensure timezone-naive dates for merging
        df.index = df.index.tz_localize(None)

        # Technical Indicators
        df['SMA_20'] = df['Close'].rolling(window=20).mean()
        df['SMA_50'] = df['Close'].rolling(window=50).mean()
        
        # Calculate RSI (14-day)
        delta = df['Close'].diff()
        gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
        loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
        rs = gain / loss
        df['RSI'] = 100 - (100 / (1 + rs))
        
        # Calculate MACD
        exp1 = df['Close'].ewm(span=12, adjust=False).mean()
        exp2 = df['Close'].ewm(span=26, adjust=False).mean()
        df['MACD'] = exp1 - exp2
        df['Signal_Line'] = df['MACD'].ewm(span=9, adjust=False).mean()
        
        # Target: 1 if tomorrow's Close > today's Close, 0 otherwise
        df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)
        
        # Target_Reg: Percentage change from today's close to tomorrow's close
        df['Target_Reg'] = ((df['Close'].shift(-1) - df['Close']) / df['Close']) * 100
        
        # Drop NaN values generated by rolling windows and shift
        df.dropna(inplace=True)
        
        df.reset_index(inplace=True)
        # Rename Date column to ensure standard formatting
        if 'Date' in df.columns:
            df['Date'] = pd.to_datetime(df['Date']).dt.date
        return df

    def fetch_news(self):
        """
        Fetches company news from Finnhub. Uses mock data if API key is missing or fails.
        """
        print(f"Fetching news for {self.ticker}...")
        if not self.finnhub_client:
            print("No FINNHUB_API_KEY found, using mock news data for demonstration.")
            return self._generate_mock_news()
            
        try:
            # Finnhub takes dates in YYYY-MM-DD
            news = self.finnhub_client.company_news(self.ticker, _from=self.start_date, to=self.end_date)
            if not news:
                print("No news returned from Finnhub, using mock.")
                return self._generate_mock_news()
                
            news_df = pd.DataFrame(news)
            # Convert Unix timestamps to Date objects
            news_df['datetime'] = pd.to_datetime(news_df['datetime'], unit='s')
            news_df['Date'] = news_df['datetime'].dt.date
            news_df.rename(columns={'headline': 'title'}, inplace=True)
            
            return news_df[['Date', 'title', 'summary']]
            
        except Exception as e:
            print(f"Error fetching news from Finnhub: {e}. Using mock news.")
            return self._generate_mock_news()

    def _generate_mock_news(self):
        """
        Generates sensible mock news headlines to allow the project to run without APIs.
        """
        dates = pd.date_range(start=self.start_date, end=self.end_date, freq='D')
        data = []
        import random
        # Seed for reproducibility based on ticker
        random.seed(sum(ord(c) for c in self.ticker))
        
        headlines_pool = [
            (f"{self.ticker} announces record-breaking quarterly revenue.", "Positive performance expected."),
            (f"Analysts downgrade {self.ticker} amid supply chain concerns.", "Negative outlook on operations."),
            (f"{self.ticker} CEO unveils new strategic product roadmap.", "Market optimistic about new launches."),
            (f"Legal challenges ahead for {self.ticker} over patent disputes.", "Investors anxious regarding pending litigation."),
            (f"{self.ticker} merges with key competitor to consolidate market share.", "Massive shift in industry landscape."),
            (f"Steady trading continues for {self.ticker} with no major updates.", "Market remains neutral today.")
        ]
        
        for d in dates:
            # Pick 1 to 3 random headlines per day
            num_articles = random.randint(1, 3)
            samples = random.sample(headlines_pool, num_articles)
            for title, summary in samples:
                data.append({'Date': d.date(), 'title': title, 'summary': summary})
                
        return pd.DataFrame(data)

if __name__ == "__main__":
    # Test Data Collector
    dc = DataCollector("AAPL", start_date="2023-01-01", end_date="2023-02-01")
    stock_df = dc.fetch_stock_data()
    print("Stock Data Head:")
    print(stock_df.head())
    
    news_df = dc.fetch_news()
    print("\nNews Data Head:")
    print(news_df.head())
